#!/usr/bin/env node
// Assemble the deployable site into _site/.
//
// Copies exactly what the runtime needs (see the module graph in the readme):
//   index.html            dist/index.html when HtmlWebpackPlugin generates one,
//                         otherwise the root index.html
//   dist/**               webpack bundle (hashed main/timer)
//   spin/spin-proc.js     unbundled worklet (loaded via audioWorklet.addModule)
//   spin/spin.js          (kept for parity with the documented runtime graph)
//   spin/spin-structs.js  imported by spin-proc.js
//   spin/spin.wasm.js     imported by spin-proc.js
//   src/midilist.js       imported by spin-proc.js
//   mfilelist.js, sflist.js  imported by midilist.js (generated by webpack build)
//   saturation/index.js   imported by spin-proc.js
//   saturation/saturate.wasm.js  imported by saturation/index.js
//   lpf/lpf-proc.js       unbundled worklet
//   lpf/lpf.wasm.js       passed to lpf-proc.js via processorOptions
//   static/**             SoundFonts, MIDI, served with Range requests
//   docs/ui-reference.html  static layout reference
//   .nojekyll             GitHub Pages: don't run Jekyll
//
// Cache-busting: relative import specifiers inside the copied unbundled .js
// files get `?v=<build-id>` appended, so a rebuilt spin.wasm.js is actually
// fetched fresh (the addModule URLs themselves are busted via DefinePlugin
// __BUILD_ID__ at bundle time). dist/** is already content-hashed by webpack.
//
// Usage: node tools/assemble-site.mjs --root <repo> --out <_site dir> --build-id <id>
import { cpSync, existsSync, mkdirSync, readdirSync, readFileSync, rmSync, writeFileSync } from "node:fs";
import { dirname, join, resolve } from "node:path";

function arg(name) {
  const i = process.argv.indexOf(name);
  if (i < 0 || !process.argv[i + 1]) {
    console.error(`missing ${name} <value>`);
    process.exit(1);
  }
  return process.argv[i + 1];
}

const root = resolve(arg("--root"));
const out = resolve(arg("--out"));
const buildId = arg("--build-id");

const UNBUNDLED_JS = [
  "spin/spin-proc.js",
  "spin/spin.js",
  "spin/spin-structs.js",
  "spin/spin.wasm.js",
  "src/midilist.js",
  "mfilelist.js",
  "sflist.js",
  "saturation/index.js",
  "saturation/saturate.wasm.js",
  "lpf/lpf-proc.js",
  "lpf/lpf.wasm.js",
];

function copyInto(rel) {
  const from = join(root, rel);
  if (!existsSync(from)) {
    console.error(`assemble-site: required file missing: ${rel}`);
    process.exit(1);
  }
  const to = join(out, rel);
  mkdirSync(dirname(to), { recursive: true });
  cpSync(from, to, { recursive: true });
}

rmSync(out, { recursive: true, force: true });
mkdirSync(out, { recursive: true });

// webpack output (whatever it emitted: hashed or plain names)
copyInto("dist");
// index.html: prefer the HtmlWebpackPlugin output, fall back to the template.
// The plugin emits asset URLs relative to dist/ (e.g. src="main.<hash>.js"),
// so when the file moves to the site root they must be rewritten to dist/.
if (existsSync(join(root, "dist", "index.html"))) {
  const html = readFileSync(join(root, "dist", "index.html"), "utf8").replace(
    /(src|href)="((?!https?:\/\/|\/|dist\/)[^"]+)"/g,
    '$1="dist/$2"',
  );
  writeFileSync(join(out, "index.html"), html);
} else {
  copyInto("index.html");
}
for (const rel of UNBUNDLED_JS) copyInto(rel);
copyInto("static");
if (existsSync(join(root, "docs", "ui-reference.html"))) {
  copyInto("docs/ui-reference.html");
}
writeFileSync(join(out, ".nojekyll"), "");

// Cache-bust relative imports inside the unbundled JS (not dist/**).
const importRe = /(from\s*["']|import\s*["'])(\.[^"']+?)(["'])/g;
for (const rel of UNBUNDLED_JS) {
  if (!rel.endsWith(".js")) continue;
  const file = join(out, rel);
  const src = readFileSync(file, "utf8");
  const next = src.replace(importRe, (m, pre, spec, quote) => {
    if (spec.includes("?") || spec.includes("://")) return m;
    return `${pre}${spec}?v=${buildId}${quote}`;
  });
  if (next !== src) writeFileSync(file, next);
}

const count = readdirSync(out).length;
console.log(`site assembled in ${out} (${count} top-level entries, build ${buildId})`);
